name: Test Performance Benchmark

on: 
  push:
  workflow_dispatch:
    inputs:
      test_runs:
        description: "Number of times to run each test"
        required: false
        default: 10
        type: number

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        tool: [playwright, cypress, selenium]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Set Test Iterations Environment Variable
        run: echo "TEST_RUNS=${{ github.event.inputs.test_runs }}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright
        run: npx playwright install

      - name: Run Playwright Tests
        if: matrix.tool == 'playwright'
        run: |
          START=$(date +%s)
          TEST_RUNS=${{ github.event.inputs.test_runs }} node playwright_test.js
          END=$(date +%s)
          PLAYWRIGHT_TIME=$((END-START))
          echo "PLAYWRIGHT_TIME=$PLAYWRIGHT_TIME" >> execution_times.txt

      - name: Run Cypress Tests
        if: matrix.tool == 'cypress'
        run: |
          START=$(date +%s)
          npx cypress run --quiet --browser chrome TEST_RUNS=${{ github.event.inputs.test_runs }} 
          END=$(date +%s)
          CYPRESS_TIME=$((END-START))
          echo "CYPRESS_TIME=$CYPRESS_TIME" >> execution_times.txt

      - name: Run Selenium Tests
        if: matrix.tool == 'selenium'
        run: |
          START=$(date +%s)
          TEST_RUNS=${{ github.event.inputs.test_runs }} node selenium_test.js
          END=$(date +%s)
          SELENIUM_TIME=$((END-START))
          echo "SELENIUM_TIME=$SELENIUM_TIME" >> execution_times.txt
      