name: Test Performance Benchmark

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tool: [playwright, cypress, selenium]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        if: matrix.tool == 'playwright'
        run: npx playwright install --with-deps

      - name: Run Playwright Tests (10 times)
        if: matrix.tool == 'playwright'
        run: |
          for i in {1..10}
          do
            echo "Run #$i"
            node playwright_test.js
          done

      - name: Run Cypress Tests (10 times)
        if: matrix.tool == 'cypress'
        run: |
          for i in {1..10}
          do
            echo "Run #$i"
            npx cypress run --quiet --browser chrome
          done

      - name: Run Selenium Tests (10 times)
        if: matrix.tool == 'selenium'
        run: |
          for i in {1..10}
          do
            echo "Run #$i"
            node selenium_test.js
          done
