name: Test Performance Benchmark

on: 
  push:
  workflow_dispatch:
    inputs:
      test_runs:
        description: "Number of times to run each test"
        required: false
        default: 10
        type: number

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        tool: [playwright, cypress, selenium]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Set Test Iterations Environment Variable
        run: echo "TEST_RUNS=${{ github.event.inputs.test_runs }}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright
        run: npx playwright install

      - name: Run Playwright Tests
        if: matrix.tool == 'playwright'
        run: |
          START=$(date +%s)
          TEST_RUNS=${{ github.event.inputs.test_runs }} node playwright_test.js
          END=$(date +%s)
          PLAYWRIGHT_TIME=$((END-START))
          echo "PLAYWRIGHT_TIME=$PLAYWRIGHT_TIME" >> execution_times.txt

      - name: Run Cypress Tests
        if: matrix.tool == 'cypress'
        run: |
          START=$(date +%s)
          TEST_RUNS=${{ github.event.inputs.test_runs }} npx cypress run --quiet --browser chrome TEST_RUNS=$TEST_RUNS
          END=$(date +%s)
          CYPRESS_TIME=$((END-START))
          echo "CYPRESS_TIME=$CYPRESS_TIME" >> execution_times.txt

      - name: Run Selenium Tests
        if: matrix.tool == 'selenium'
        run: |
          START=$(date +%s)
          TEST_RUNS=${{ github.event.inputs.test_runs }} node selenium_test.js
          END=$(date +%s)
          SELENIUM_TIME=$((END-START))
          echo "SELENIUM_TIME=$SELENIUM_TIME" >> execution_times.txt
      
      - name: Upload Execution Times as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: execution-times
          path: execution_times.txt
  
  generate-chart:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Execution Times
        uses: actions/download-artifact@v4
        with:
          name: execution-times
      
      - name: Read Execution Times and Set Environment Variables
        run: |
          cat execution_times.txt
          export $(cat execution_times.txt | xargs)
        
      - name: Install Python and Dependencies
        run: |
          sudo apt update
          sudo apt install python3 python3-pip -y
          pip install matplotlib

      - name: Generate Bar Chart
        run: python3 generate_chart.py

      - name: Upload Chart as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: execution-time-chart
          path: execution_time_chart.png
